import { supabase } from './supabase';

/**
 * The client's entire AI surface.
 *
 * It can name an operation and a group — nothing else. No prompt, no model,
 * no message selection, and no API key: all of that lives in the `gc-ai` edge
 * function, which re-checks membership under the caller's own token before
 * spending anything. Adding a feature means adding an operation server-side
 * and a name to `AIOperationName`, not new client capability.
 */

export type AIOperationName =
  | 'test_summary'
  | 'what_did_i_miss'
  | 'daily_recap'
  | 'gc_command'
  | 'tea_report'
  | 'poll_draft'
  // System-only: generated by the weekly scheduler, never invoked by a
  // client. Listed for type-completeness, not because the app ever calls it.
  | 'weekly_gc_awards'
  // System-only, like weekly_gc_awards: generated as part of the weekly
  // awards run. The DNA screen reads the stored snapshot, it never asks for
  // a generation — there is no client path to this operation at all.
  | 'gc_dna'
  // Planned — each needs a matching operation in supabase/functions/gc-ai.
  | 'explain_lore'
  | 'find_receipt'
  | 'member_personality';

export type AIErrorCode =
  | 'unauthorized'
  | 'not_a_member'
  | 'group_not_found'
  | 'unknown_operation'
  | 'invalid_request'
  | 'rate_limited'
  | 'empty_context'
  | 'context_too_large'
  | 'provider_unavailable'
  | 'provider_timeout'
  | 'invalid_ai_response'
  | 'internal';

export type AIError = {
  code: AIErrorCode;
  retryable: boolean;
  retryAfterSeconds?: number;
};

export type AIResponse<T> =
  | { ok: true; cached: boolean; operation: string; result: T }
  | { ok: false; error: AIError };

/** An AI claim tied back to the messages that support it. The ids are the
 *  same ids the chat's jumpToMessage already takes. */
export type SourcedInsight = {
  text: string;
  sourceMessageIds: string[];
};

export type TestSummaryResult = {
  summary: string;
  highlights: SourcedInsight[];
};

/** Badge categories the recap UI knows how to render. */
export type MissedCategory =
  | 'tea'
  | 'plan'
  | 'info'
  | 'funny'
  | 'convo'
  | 'pinned'
  | 'mention';

export type MissedHighlight = {
  category: MissedCategory;
  title: string;
  summary: string;
  /** Always real, server-validated ids — safe to pass to jumpToMessage. */
  messageIds: string[];
};

export type WhatDidIMissResult = {
  hasMissedContent: boolean;
  headline: string;
  summary: string;
  highlights: MissedHighlight[];
  mentionedMessageIds: string[];
  pinnedMessageIds: string[];
  /** The missed range was too long to summarize whole. */
  truncated: boolean;
  messageCount: number;
};

/** What kind of question @gc decided it was answering. Surfaced mostly for
 *  debugging/telemetry — the UI renders every intent the same way. */
export type GCIntent =
  | 'summary'
  | 'conversation_analysis'
  | 'message_search'
  | 'lore'
  | 'current_context'
  | 'general';

export type GCCommandResult = {
  intent: GCIntent;
  text: string;
  /** Server-validated against the context — safe to pass to jumpToMessage. */
  sourceMessageIds: string[];
  /** The model said the messages didn't actually answer the question. */
  insufficientContext: boolean;
};

export type AwardType =
  | 'professional_yapper'
  | 'professional_lurker'
  | 'most_unhinged'
  | 'drama_starter'
  | 'fastest_reply'
  | 'message_of_week'
  | 'night_owl'
  | 'voice_note_menace'
  | 'media_spammer'
  | 'sticker_of_week'
  | 'most_active'
  | 'most_reliable'
  | 'one_liner_king'
  | 'funniest_member'
  | 'fact_checker'
  | 'lore_keeper'
  | 'npc_of_the_week';

export type Award = {
  type: AwardType;
  emoji: string;
  title: string;
  userId: string | null;
  userName: string;
  userAvatarEmoji: string | null;
  userAvatarColor: string | null;
  userAvatarUrl: string | null;
  value: string | null;
  /** Set only where the award's subject is a thing rather than a person —
   *  Sticker of the Week shows the sticker here instead of an avatar.
   *  Optional because awards generated before this existed have no such
   *  field in their stored JSON. */
  imageUrl?: string | null;
  reason: string;
  sourceMessageIds: string[];
};

export type WeeklyAwardsStatus = 'generating' | 'completed' | 'failed';

export type WeeklyAwardsResult = {
  groupId: string;
  weekStart: string;
  weekEnd: string;
  status: WeeklyAwardsStatus;
  messageCount: number;
  generatedAt: string | null;
  /** GC's own overall take on the week — null while still generating/failed. */
  title: string | null;
  summary: string | null;
  awards: Award[];
};

export type TeaPerson = {
  userId: string | null;
  name: string;
  role: string;
  messageIds: string[];
};

export type TeaPlotTwist = {
  text: string;
  messageIds: string[];
};

export type TeaReportResult = {
  title: string;
  summary: string;
  people: TeaPerson[];
  plotTwists: TeaPlotTwist[];
  /** 1–5, honest rather than flattering — a quiet session really does get a 1. */
  dramaLevel: number;
  outcome: string;
  receiptMessageIds: string[];
  messageCount: number;
};

export type DailyRecapPerson = {
  userId: string;
  name: string;
  avatarEmoji: string | null;
  avatarColor: string | null;
  avatarUrl: string | null;
  messageCount: number;
};

export type DailyRecapMessage = {
  messageId: string;
  sender: string;
  text: string;
  reactionCount: number;
};

export type DailyRecapPick = {
  caption: string;
  messageId: string;
};

export type DailyRecapResult = {
  date: string;
  totalMessages: number;
  truncated: boolean;
  userOfTheDay: DailyRecapPerson | null;
  messageOfTheDay: DailyRecapMessage | null;
  oneWord: string;
  bestTea: DailyRecapPick | null;
  mostUnhinged: DailyRecapPick | null;
};

/** A poll drafted by @gc. Nothing is created until the user confirms it in
 *  the normal poll editor — see PollComposer. */
export type PollDraftResult = {
  question: string;
  options: string[];
  allowMultiple: boolean;
  /** The request was too vague to draft from honestly. */
  needsClarification: boolean;
  clarification: string;
};

/**
 * 🧬 GC DNA — the group's personality, as stored by the weekly awards run.
 *
 * Read from `group_dna`, never requested: there is no client path that can
 * cause a generation, which is what "no Update DNA button" means in practice.
 */
export type DNAScores = Record<string, number>;

export type GroupDNAArchetype = {
  id: string;
  name: string;
  emoji: string;
  description: string;
};

export type GroupDNA = {
  version: number;
  /** False is a real, expected state — a young GC has no personality yet. */
  enoughData: boolean;
  archetype: GroupDNAArchetype | null;
  /** Keyed by dimension (chaos, yapping, …). Every value is 0–100 and was
   *  computed in SQL, never by the model. */
  scores: DNAScores;
  communicationStyle: {
    summary: string;
    stats: {
      averageMessageLength: number;
      shortMessageRate: number;
      mediaRate: number;
      replyRate: number;
      reactionRate: number;
    };
  };
  /** Each observation's ids are server-validated — safe for jumpToMessage. */
  definesThisGC: SourcedInsight[];
  oneLiner: string;
  stats: Record<string, unknown>;
};

/**
 * Display metadata for every DNA dimension, mirroring DNA_DIMENSIONS in the
 * edge function. Kept as a list so the screen renders in a fixed order and an
 * older snapshot missing a newer key is simply skipped rather than breaking.
 */
export const DNA_DIMENSIONS: { key: string; emoji: string; label: string }[] = [
  { key: 'chaos', emoji: '💀', label: 'Chaos' },
  { key: 'yapping', emoji: '🗣️', label: 'Yapping' },
  { key: 'tea', emoji: '🍵', label: 'Tea' },
  { key: 'wholesome', emoji: '❤️', label: 'Wholesome' },
  { key: 'organization', emoji: '📅', label: 'Organized' },
  { key: 'nightOwl', emoji: '🌙', label: 'Night Owl' },
  { key: 'lurking', emoji: '👻', label: 'Lurkers' },
  { key: 'responsiveness', emoji: '⚡', label: 'Reply Speed' },
  { key: 'memeEnergy', emoji: '🎭', label: 'Meme Energy' },
  { key: 'visual', emoji: '📸', label: 'Visual' },
  { key: 'voiceNotes', emoji: '🎙️', label: 'Voice Notes' },
  { key: 'consistency', emoji: '🔥', label: 'Consistency' },
  { key: 'depth', emoji: '💬', label: 'Depth' },
  { key: 'hype', emoji: '🎉', label: 'Hype' },
  { key: 'balance', emoji: '🤝', label: 'Balance' },
  { key: 'broadcast', emoji: '📢', label: 'Broadcast' },
];

/**
 * Copy for each failure, in GC's voice. Keyed by code rather than by the
 * server's message, so no provider error text can ever surface to a user.
 */
const ERROR_COPY: Record<AIErrorCode, string> = {
  unauthorized: 'Sign in again and give it another go.',
  not_a_member: "You're not in this GC anymore.",
  group_not_found: "Couldn't find that GC.",
  unknown_operation: "GC AI doesn't know how to do that yet.",
  invalid_request: 'Something about that request was off.',
  rate_limited: "You've been asking a lot. Give it a minute 😮‍💨",
  empty_context: 'Nothing to read here yet — go say something first.',
  context_too_large: "That's way too much chat to read at once.",
  provider_unavailable: 'GC AI is taking a nap 😭 Try again in a moment.',
  provider_timeout: 'GC AI took too long thinking. Try again.',
  invalid_ai_response: 'GC AI said something incoherent. Try again.',
  internal: 'Something broke on our end 💀 Try again in a moment.',
};

export function aiErrorMessage(error: AIError | null | undefined): string {
  if (!error) return ERROR_COPY.internal;
  return ERROR_COPY[error.code] ?? ERROR_COPY.internal;
}

/**
 * Calls the AI edge function. Never throws — every path resolves to an
 * `AIResponse`, so a screen can render an error state without a try/catch
 * around its own render logic.
 */
export async function invokeGCAI<T>(
  groupId: string,
  operation: AIOperationName,
  params?: Record<string, unknown>
): Promise<AIResponse<T>> {
  try {
    const { data, error } = await supabase.functions.invoke('gc-ai', {
      body: { groupId, operation, params },
    });

    // A non-2xx carries our structured error in the body, which
    // functions.invoke surfaces as a generic FunctionsHttpError — dig the
    // real code out of the response rather than reporting a bare failure.
    if (error) {
      const parsed = await parseFunctionError(error);
      return { ok: false, error: parsed };
    }

    if (data && typeof data === 'object' && 'ok' in data) {
      return data as AIResponse<T>;
    }

    return { ok: false, error: { code: 'internal', retryable: true } };
  } catch {
    // Offline, DNS, TLS — indistinguishable from here and all worth retrying.
    return { ok: false, error: { code: 'provider_unavailable', retryable: true } };
  }
}

async function parseFunctionError(error: unknown): Promise<AIError> {
  const response = (error as { context?: Response })?.context;
  if (response && typeof response.json === 'function') {
    try {
      const body = await response.json();
      if (body?.error?.code) return body.error as AIError;
    } catch {
      // Fall through to the generic error below.
    }
  }
  return { code: 'internal', retryable: true };
}
