const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** Matches the Podfile's own `platform :ios, ... || '15.1'` default. */
const MIN_TARGET = '15.1';
const MARKER = '# gc: bump stale pod deployment targets';

/**
 * Forces every CocoaPods target — including resource bundle targets — up to
 * MIN_TARGET.
 *
 * Why this is needed: some podspecs still declare an ancient minimum (e.g.
 * @react-native-async-storage/async-storage says `ios: '13.4'`). React
 * Native's own `updateOSDeploymentTarget` only walks
 * `pod_target_installation_results[].native_target`, so it never visits a
 * pod's `resource_bundle_targets`. That leaves targets like
 * `RNCAsyncStorage-RNCAsyncStorage_resources` pinned at 13.4, and Xcode 26+
 * (minimum supported deployment target 15.0) hard-fails the build with
 * "the range of supported deployment target versions is 15.0 to 27.0.x".
 *
 * `installer.pods_project.targets` covers main pod targets *and* resource
 * bundles, so bumping there catches both. Runs after
 * `react_native_post_install` so it always gets the last write.
 *
 * This lives as a config plugin rather than a hand-edit to ios/Podfile
 * because that file is regenerated by `expo prebuild` — a manual edit there
 * silently disappears on the next clean build.
 */
const SNIPPET = `
    ${MARKER}
    installer.pods_project.targets.each do |pod_target|
      pod_target.build_configurations.each do |pod_config|
        current = pod_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if current.nil? || current.to_f < ${MIN_TARGET}
          pod_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${MIN_TARGET}'
        end
      end
    end
`;

module.exports = function withIosDeploymentTarget(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfilePath, 'utf8');

      if (contents.includes(MARKER)) return cfg;

      // Append right after the react_native_post_install(...) call so our
      // values win over anything RN sets.
      const rnPostInstall = /(react_native_post_install\([\s\S]*?\n\s*\)\n)/;
      let next;
      if (rnPostInstall.test(contents)) {
        next = contents.replace(rnPostInstall, `$1${SNIPPET}`);
      } else {
        // Fallback: the generated template changed shape — put it at the top
        // of post_install instead of silently doing nothing.
        next = contents.replace(
          /(post_install do \|installer\|\n)/,
          `$1${SNIPPET}`
        );
      }

      if (next === contents) {
        throw new Error(
          '[withIosDeploymentTarget] Could not find a post_install block in ios/Podfile to patch.'
        );
      }

      fs.writeFileSync(podfilePath, next);
      return cfg;
    },
  ]);
};
